#!/usr/bin/env python
"""Clear tenant schema and re-migrate."""
import os
import django

os.environ['TENANT_DB_ALIAS'] = 'tenant_1'
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from django.db import connections
from django.core.management import call_command
from tenancy.models import Tenant

# Get tenant
from tenancy.models import Shop

tenant = Tenant.objects.get(id=1)  # tenant_1 = Volt
alias = tenant.db_alias

# Get a shop to get the schema name (or use the first active shop)
shop = tenant.shops.filter(is_active=True).first()
if not shop:
    print("ERROR: No active shops found for this tenant")
    exit(1)
schema_name = shop.schema_name

print(f"=" * 70)
print(f"Cleaning tenant schema: {schema_name}")
print(f"Database alias: {alias}")
print(f"=" * 70)

conn = connections[alias]
cursor = conn.cursor()

# Get all tables in the tenant schema
print(f"\nGetting all tables in schema '{schema_name}'...")
cursor.execute("""
    SELECT table_name FROM information_schema.tables 
    WHERE table_schema = %s 
    AND table_type = 'BASE TABLE'
    ORDER BY table_name
""", [schema_name])

tables = [row[0] for row in cursor.fetchall()]
print(f"Found {len(tables)} tables to drop:")
for table in tables:
    print(f"  - {table}")

# Drop all tables
if tables:
    print(f"\nDropping all tables in schema '{schema_name}'...")
    # Disable foreign key constraints temporarily
    cursor.execute(f"SET CONSTRAINTS ALL DEFERRED")
    
    for table in tables:
        try:
            cursor.execute(f'DROP TABLE IF EXISTS "{schema_name}"."{table}" CASCADE')
            print(f"  ✓ Dropped {table}")
        except Exception as e:
            print(f"  ✗ Error dropping {table}: {e}")
    
    conn.commit()
    print("✓ All tables dropped")

# Also drop auth and contenttypes from public schema to allow fresh migration
print(f"\nDropping auth and contenttypes tables from public schema...")
public_tables_to_drop = [
    'django_content_type', 'auth_group', 'auth_group_permissions',
    'auth_permission', 'auth_user', 'auth_user_groups', 'auth_user_user_permissions',
    'django_admin_log'
]
for table in public_tables_to_drop:
    try:
        cursor.execute(f'DROP TABLE IF EXISTS "{table}" CASCADE')
        print(f"  ✓ Dropped {table}")
    except Exception as e:
        pass  # Ignore if table doesn't exist
conn.commit()

# Clear migration records
print(f"\nClearing migration records...")
cursor.execute("DELETE FROM django_migrations")
conn.commit()
print("✓ Migration records cleared")

# Recreate django_migrations table if needed
cursor.execute("""
    CREATE TABLE IF NOT EXISTS django_migrations (
        id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        app character varying(255) NOT NULL,
        name character varying(255) NOT NULL,
        applied timestamp with time zone NOT NULL
    )
""")
conn.commit()
print("✓ django_migrations table ready")

# Now re-run migrations
print(f"\n" + "=" * 70)
print("Re-migrating all apps...")
print("=" * 70)

apps_in_order = [
    'auth', 'contenttypes', 'admin', 'token_blacklist', 
    'shop_users', 'cash_book', 'debtors', 'creditors', 
    'stock_control', 'purchase_orders', 'pos', 'settings'
]

os.environ['TENANT_DB_ALIAS'] = alias

for app in apps_in_order:
    print(f"\n  Applying {app}...")
    try:
        call_command('migrate', app, database=alias, verbosity=1)
        print(f"  ✓ {app} migrated")
    except Exception as e:
        error_msg = str(e).split('\n')[0][:80]
        print(f"  ✗ {app} error: {error_msg}")
        # Continue with next app
        continue

print(f"\n" + "=" * 70)
print(f"✓ All migrations completed for tenant schema '{schema_name}'")
print(f"=" * 70)

# Show final table count
cursor.execute(f"""
    SELECT COUNT(*) FROM information_schema.tables 
    WHERE table_schema = %s AND table_type = 'BASE TABLE'
""", [schema_name])
table_count = cursor.fetchone()[0]
print(f"\nFinal table count in schema '{schema_name}': {table_count}")
