# Generated by Django 5.2.7 on 2026-03-18 10:30

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_invoiceline_line_cost_and_more'),
        ('settings', '0005_systemconfiguration_day_end_day_of_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LaybyelPayment',
            new_name='LaybyePayment',
        ),
        migrations.RenameField(
            model_name='quotationline',
            old_name='discount_amount',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='laybyeline',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='laybyeline',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='laybyeline',
            name='tax_code',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='laybyeline',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laybyeline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='VAT Amount (14%)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Total Cost (quantity × cost_price)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_profit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Line Profit (line_total - line_cost)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_total',
            field=models.DecimalField(decimal_places=4, help_text='Line Total (excl. VAT, after discount)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='vat_amount',
            field=models.DecimalField(decimal_places=4, help_text='VAT Amount for this line', max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('14.00'), help_text='VAT Rate % (14% South African VAT)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='laybye',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='laybyeline',
            name='laybye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.laybye'),
        ),
        migrations.AlterField(
            model_name='laybyeline',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='quotationline',
            name='tax_code',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
