# Generated by Django 5.2.7 on 2026-03-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0008_rename_laybyelpayment_laybyepayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CONVERTED_TO_INVOICE", "Converted to Invoice"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="laybye",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                ],
                default="ACTIVE",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INVOICED", "Invoiced"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("JOB", "Converted to Job"),
                ],
                default="ACTIVE",
                max_length=25,
            ),
        ),
    ]
