# Generated by Django 5.2.7 on 2026-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0010_laybye_debtor_account_number_alter_laybye_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laybye",
            name="debtor_account_number",
            field=models.IntegerField(
                blank=True, help_text="Customer account number (DNO)", null=True
            ),
        ),
    ]
