# Generated by Django 5.2.7 on 2026-08-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0012_cashacheque_cancel_reason_cashacheque_cancelled_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CONVERTED_TO_INVOICE", "Converted to Invoice"),
                    ("CONVERTED_TO_CASH_SALE", "Converted to Cash Sale"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=25,
            ),
        ),
    ]
