# Generated by Django 5.2.7 on 2026-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0013_alter_jobcard_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CONVERTED_TO_INVOICE", "Converted to Invoice"),
                    ("CONVERTED_TO_CASH_SALE", "Converted to Cash Sale"),
                    ("INVOICED", "Invoiced"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("JOB", "Converted to Job"),
                ],
                default="ACTIVE",
                max_length=25,
            ),
        ),
    ]
