# Generated by Django 5.2.7 on 2026-08-31 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin - Full tenant access"),
                            ("MANAGER", "Manager - Can manage shop users"),
                            ("STAFF", "Staff - Staff member with limited access"),
                            ("CASHIER", "Cashier - Basic access"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("pos", "Point of Sale"),
                            ("debtors", "Debtors"),
                            ("creditors", "Creditors"),
                            ("cash_book", "Cash Book"),
                            ("general_ledger", "General Ledger"),
                            ("stock_control", "Stock Control"),
                            ("purchase_orders", "Purchase Orders"),
                            ("settings", "Utilities"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "function_type",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE", "Maintenance"),
                            ("TRANSACTIONS", "Transactions"),
                            ("ENQUIRY", "Enquiry"),
                            ("REPORT", "Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_allowed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Access Grant",
                "verbose_name_plural": "Access Grants",
                "db_table": "access_grants",
                "ordering": ["role", "module", "function_type"],
                "indexes": [
                    models.Index(
                        fields=["role", "module", "function_type"],
                        name="access_gran_role_a787e1_idx",
                    )
                ],
                "unique_together": {("role", "module", "function_type")},
            },
        ),
    ]
