# Generated by Django 5.2.7 on 2026-01-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this tenant is active"
            ),
        ),
    ]
