# Generated by Django 5.2.7 on 2026-01-30 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_shop_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('PERMISSION_CHANGE', 'Permission Changed'), ('ROLE_CHANGE', 'Role Changed'), ('TENANT_ACCESS', 'Cross-Tenant Access Attempt'), ('DATA_ACCESS', 'Sensitive Data Access'), ('PASSWORD_CHANGE', 'Password Changed')], max_length=20)),
                ('resource_type', models.CharField(blank=True, help_text="Model name (e.g., 'ShopUser', 'Shop')", max_length=50)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('tenant_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context (JSON)')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'indexes': [models.Index(fields=['timestamp'], name='tenancy_aud_timesta_02256b_idx'), models.Index(fields=['user', 'timestamp'], name='tenancy_aud_user_id_bbdc4b_idx'), models.Index(fields=['action', 'timestamp'], name='tenancy_aud_action_ff4aee_idx'), models.Index(fields=['tenant_id', 'timestamp'], name='tenancy_aud_tenant__324d97_idx')],
            },
        ),
    ]
