# Generated by Django 5.2.7 on 2026-01-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_shop_is_active'),
    ]

    operations = [
    ]
