# Generated by Django 5.2.7 on 2026-01-30 16:27
# This migration is now a no-op because AuditLog table creation is deferred
# to 0005_create_auditlog_table to avoid circular FK dependencies

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_shop_is_active'),
    ]

    operations = [
        # No-op: real table creation moved to 0005_create_auditlog_table
    ]
