# Generated by Django 5.2.7 on 2026-01-30 14:24
# This migration is now a no-op because the AuditLog table is created
# by 0005_create_auditlog_table which handles it manually without FK dependencies

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_create_auditlog_table'),
    ]

    operations = [
        # No-op: table already created by 0005_create_auditlog_table
    ]
