# Generated by Django 5.2.7 on 2026-02-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_ignore_auditlog'),
        ('tenancy', '0005_create_auditlog_table'),
        ('tenancy', '0006_auditlog'),
    ]

    operations = [
    ]
