# Generated by Django 5.2.7 on 2026-02-04 13:31
# This migration is a no-op because the AuditLog table is already created
# by 0005_create_auditlog_table which uses raw SQL

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0007_merge_20260204_1514"),
    ]

    operations = [
        # No-op: table already created by 0005_create_auditlog_table
    ]
