# Generated by Django 5.2.7 on 2026-02-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_shop_setup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='db_host',
            field=models.CharField(default='postgres', max_length=200),
        ),
    ]
