# Generated by Django 5.2.7 on 2026-03-04 16:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0011_alter_tenant_db_host"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_day_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last successful day-end process",
                        null=True,
                    ),
                ),
                (
                    "last_month_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last successful month-end process",
                        null=True,
                    ),
                ),
                (
                    "last_year_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last successful year-end process",
                        null=True,
                    ),
                ),
                (
                    "enable_auto_day_end",
                    models.BooleanField(
                        default=False, help_text="Enable automatic day-end process"
                    ),
                ),
                (
                    "day_end_time",
                    models.TimeField(
                        default="23:59",
                        help_text="Time to run automatic day-end (HH:MM)",
                    ),
                ),
                (
                    "day_end_day_of_week",
                    models.JSONField(
                        default=list,
                        help_text="Days of week to run day-end [0=Mon, 6=Sun]",
                    ),
                ),
                (
                    "enable_auto_month_end",
                    models.BooleanField(
                        default=False, help_text="Enable automatic month-end process"
                    ),
                ),
                (
                    "month_end_day",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Day of month to run month-end (1-28)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "month_end_time",
                    models.TimeField(
                        default="23:00",
                        help_text="Time to run automatic month-end (HH:MM)",
                    ),
                ),
                (
                    "enable_auto_year_end",
                    models.BooleanField(
                        default=False, help_text="Enable automatic year-end process"
                    ),
                ),
                (
                    "year_end_month",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Month to run year-end (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "year_end_day",
                    models.PositiveIntegerField(
                        default=31,
                        help_text="Day of month to run year-end",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "year_end_time",
                    models.TimeField(
                        default="22:00",
                        help_text="Time to run automatic year-end (HH:MM)",
                    ),
                ),
                (
                    "current_financial_year",
                    models.PositiveIntegerField(
                        default=2024, help_text="Current financial year (e.g., 2024)"
                    ),
                ),
                (
                    "current_period",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Current accounting period (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="tenancy.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Configuration",
                "verbose_name_plural": "Shop Configurations",
                "db_table": "shop_configuration",
            },
        ),
    ]
