# Generated by Django 5.2.7 on 2026-03-05 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0012_shopconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shop logo for invoices and PDFs', null=True, upload_to='shop_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='charge_interest_on_overdue',
            field=models.BooleanField(default=False, help_text='Charge interest on overdue accounts'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_address',
            field=models.TextField(blank=True, help_text='Company address for documents'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for documents', max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='currency_code',
            field=models.CharField(default='ZAR', help_text='Currency code (ISO 4217)', max_length=3),
        ),
        migrations.AddField(
            model_name='tenant',
            name='currency_symbol',
            field=models.CharField(default='R', help_text='Currency symbol', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='decimal_places',
            field=models.PositiveIntegerField(default=2, help_text='Decimal places for currency'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='default_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default interest rate (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='financial_year_start_month',
            field=models.PositiveIntegerField(default=1, help_text='Month the financial year starts (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Company registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT registration number', max_length=50),
        ),
    ]
