# Generated by Django 5.2.7 on 2026-03-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0014_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="currency",
            field=models.CharField(
                default="ZAR", help_text="Currency code (ISO 4217)", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe price ID for this plan (cached after first use)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="ISO 2-letter country code (e.g., ZA, US) - used for payment gateway selection",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="preferred_gateway",
            field=models.CharField(
                blank=True,
                choices=[("payfast", "PayFast"), ("stripe", "Stripe")],
                help_text="Preferred payment gateway for this tenant",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe customer ID for this tenant",
                max_length=100,
            ),
        ),
    ]
