# Generated by Django 5.2.7 on 2026-09-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0018_tenant_enabled_addons"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="enable_stock_consolidation",
            field=models.BooleanField(
                default=True,
                help_text="Allow inter-branch stock transfers (Stock Consolidation) for this tenant",
            ),
        ),
    ]
