# Generated by Django 5.2.7 on 2026-01-30 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors', '0001_initial'),
        ('settings', '0001_initial'),
        ('stock_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorcreditnotelineitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditor_cn_lines', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='creditorcreditnotelineitem',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.taxcode'),
        ),
        migrations.AddField(
            model_name='creditorcreditnotelineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorinvoice',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='creditors.creditor'),
        ),
        migrations.AddField(
            model_name='creditorinvoice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorinvoicelineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorinvoicelineitem',
            name='expense_category',
            field=models.ForeignKey(limit_choices_to={'category_type__in': ['BOTH', 'CREDITORS']}, on_delete=django.db.models.deletion.PROTECT, related_name='creditor_invoice_lines', to='settings.expensecategory'),
        ),
        migrations.AddField(
            model_name='creditorinvoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='creditors.creditorinvoice'),
        ),
        migrations.AddField(
            model_name='creditorinvoicelineitem',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.taxcode'),
        ),
        migrations.AddField(
            model_name='creditorinvoicelineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorjournal',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorjournal',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='creditors.creditor'),
        ),
        migrations.AddField(
            model_name='creditorjournal',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorjournal',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditoropenitem',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='creditors.creditorcreditnote'),
        ),
        migrations.AddField(
            model_name='creditoropenitem',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='creditors.creditor'),
        ),
        migrations.AddField(
            model_name='creditoropenitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='creditors.creditorinvoice'),
        ),
        migrations.AddField(
            model_name='creditoropenitem',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='creditors.creditorjournal'),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='creditors.creditor'),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.paymentmethod'),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditorpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='creditors.creditor'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditoropenitem',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='creditors.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='creditorcreditnote',
            name='original_grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='creditors.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='creditors.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.taxcode'),
        ),
        migrations.AddField(
            model_name='grnlineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openitemallocation',
            name='open_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='creditors.creditoropenitem'),
        ),
        migrations.AddField(
            model_name='openitemallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='creditors.creditorpayment'),
        ),
        migrations.AddField(
            model_name='rfc',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfc',
            name='creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfcs', to='creditors.creditor'),
        ),
        migrations.AddField(
            model_name='rfc',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfclineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfclineitem',
            name='rfc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='creditors.rfc'),
        ),
        migrations.AddField(
            model_name='rfclineitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfc_lines', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='rfclineitem',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.taxcode'),
        ),
        migrations.AddField(
            model_name='rfclineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['supplier_number'], name='creditors_supplie_53c4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['name'], name='creditors_name_10392d_idx'),
        ),
        migrations.AddIndex(
            model_name='creditor',
            index=models.Index(fields=['is_active'], name='creditors_is_acti_f4e4c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creditorcreditnotelineitem',
            unique_together={('credit_note', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='creditorinvoicelineitem',
            unique_together={('invoice', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='grnlineitem',
            unique_together={('grn', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='rfclineitem',
            unique_together={('rfc', 'line_number')},
        ),
    ]
