# Generated by Django 5.2.7 on 2026-02-05 17:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('creditors', '0002_initial'),
        ('settings', '0002_costingcategory_costing_cat_costing_373b5f_idx_and_more'),
        ('stock_control', '0002_contractpricing_futurepricing_onetouchlookupkey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='account_type',
            field=models.CharField(choices=[('BBF', 'Balance Brought Forward'), ('OI', 'Open Item')], default='BBF', help_text='Account type (alias for account_category)', max_length=10),
        ),
        migrations.AddField(
            model_name='creditor',
            name='amount_last_paid',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Amount last paid (alias)', max_digits=15),
        ),
        migrations.AddField(
            model_name='creditor',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50),
        ),
        migrations.AddField(
            model_name='creditor',
            name='bank_branch_code',
            field=models.CharField(blank=True, help_text='Bank branch code', max_length=20),
        ),
        migrations.AddField(
            model_name='creditor',
            name='date_last_paid',
            field=models.DateField(blank=True, editable=False, help_text='Date last paid (alias)', null=True),
        ),
        migrations.AddField(
            model_name='creditor',
            name='physical_address_line3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditor',
            name='physical_postal_code',
            field=models.CharField(blank=True, help_text='Physical postal code', max_length=10),
        ),
        migrations.AddField(
            model_name='creditor',
            name='postal_address_line3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creditor',
            name='postal_postal_code',
            field=models.CharField(blank=True, help_text='Postal postal code', max_length=10),
        ),
        migrations.AddField(
            model_name='creditor',
            name='rfc_outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditor',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name for display', max_length=50),
        ),
        migrations.AddField(
            model_name='creditor',
            name='telephone1',
            field=models.CharField(blank=True, help_text='Primary telephone', max_length=20),
        ),
        migrations.AddField(
            model_name='creditor',
            name='telephone2',
            field=models.CharField(blank=True, help_text='Secondary telephone', max_length=20),
        ),
        migrations.AddField(
            model_name='creditor',
            name='vat_number',
            field=models.CharField(blank=True, help_text='VAT registration number', max_length=50),
        ),
        migrations.CreateModel(
            name='CreditorTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('amount_exclusive', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_inclusive', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='settings.expensecategory')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='stock_control.stockitem')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_lines', to='settings.taxcode')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'creditor_transaction_lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseMonthlyTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('number_of_invoices', models.PositiveIntegerField(default=0, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_totals', to='settings.expensecategory')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Monthly Total',
                'verbose_name_plural': 'Expense Monthly Totals',
                'db_table': 'expense_monthly_totals',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['expense_category', 'year', 'month'], name='expense_mon_expense_26d79b_idx'), models.Index(fields=['-year', '-month'], name='expense_mon_year_13a66d_idx')],
                'unique_together': {('expense_category', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SupplierMonthlyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('quantity_purchased', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('number_of_transactions', models.PositiveIntegerField(default=0, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_purchases', to='creditors.creditor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Monthly Purchase',
                'verbose_name_plural': 'Supplier Monthly Purchases',
                'db_table': 'supplier_monthly_purchases',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['supplier', 'year', 'month'], name='supplier_mo_supplie_f69bd4_idx'), models.Index(fields=['-year', '-month'], name='supplier_mo_year_4d3eb0_idx')],
                'unique_together': {('supplier', 'year', 'month')},
            },
        ),
    ]
