# Generated by Django 5.2.7 on 2026-03-03 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditors", "0003_remove_rfclineitem_original_transaction_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutstandingBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capture_date",
                    models.DateField(help_text="Date when balance was captured"),
                ),
                ("as_at_date", models.DateField(help_text="Balance as at this date")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total outstanding balance",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_current",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current (0-30 days)",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_30_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="30 days overdue",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_60_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="60 days overdue",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_90_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="90 days overdue",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_120_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="120 days overdue",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_150_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="150 days overdue",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_180_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="180+ days overdue",
                        max_digits=15,
                    ),
                ),
                (
                    "supplier_account_number",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's account number reference",
                        max_length=15,
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        blank=True,
                        help_text="Transaction reference number",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateField(
                        blank=True,
                        help_text="Transaction date if applicable",
                        null=True,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Original invoice amount",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Balance currently due",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "age_period",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Age period in days"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Optional notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creditor",
                    models.ForeignKey(
                        help_text="Supplier/Creditor this balance belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outstanding_balances",
                        to="creditors.creditor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Outstanding Balance",
                "verbose_name_plural": "Outstanding Balances",
                "db_table": "creditor_outstanding_balances",
                "ordering": ["-capture_date", "-as_at_date"],
                "indexes": [
                    models.Index(
                        fields=["creditor", "capture_date"],
                        name="creditor_ou_credito_85496c_idx",
                    ),
                    models.Index(
                        fields=["as_at_date"], name="creditor_ou_as_at_d_8f4631_idx"
                    ),
                ],
            },
        ),
    ]
