# Generated by Django 5.2.7 on 2026-08-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditors", "0004_outstanding_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditorjournal",
            name="age_period",
            field=models.CharField(
                choices=[
                    ("0", "Current"),
                    ("1", "30 Days"),
                    ("2", "60 Days"),
                    ("3", "90 Days"),
                    ("4", "120 Days"),
                    ("5", "150 Days"),
                    ("6", "180+ Days"),
                ],
                default="0",
                help_text="Ageing bucket this journal's full value is pinned to (Open Item accounts).",
                max_length=1,
            ),
        ),
    ]
