# Generated by Django 5.2.7 on 2026-01-30 16:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors', '0002_initial'),
        ('debtors', '0002_initial'),
        ('settings', '0001_initial'),
        ('stock_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(help_text='Purchase order number', max_length=20, unique=True)),
                ('po_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('delivery_address', models.TextField(blank=True, help_text='Delivery address (if different from default)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Supplier'), ('CONFIRMED', 'Confirmed by Supplier'), ('PARTIAL', 'Partially Received'), ('COMPLETE', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total order value (exclusive VAT)', max_digits=15)),
                ('order_total_vat', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total VAT', max_digits=15)),
                ('order_total_inclusive', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Total including VAT', max_digits=15)),
                ('total_quantity_ordered', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('total_quantity_received', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('supplier_reference', models.CharField(blank=True, help_text="Supplier's reference/quote number", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to_supplier_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='creditors.creditor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'purchase_orders',
                'ordering': ['-po_date', '-po_number'],
            },
        ),
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backorder_number', models.CharField(help_text='Back order number', max_length=20, unique=True)),
                ('backorder_date', models.DateField()),
                ('original_order_number', models.CharField(blank=True, help_text='Original sales order/invoice number', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ORDERED', 'Ordered from Supplier'), ('PARTIAL', 'Partially Received'), ('READY', 'Ready to Deliver'), ('COMPLETE', 'Delivered to Customer'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('customer_notified', models.BooleanField(default=False, help_text='Customer notified of back order')),
                ('notification_date', models.DateField(blank=True, null=True)),
                ('expected_availability_date', models.DateField(blank=True, help_text='When stock expected', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='back_orders', to='debtors.debtor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_orders', to='purchase_orders.purchaseorder')),
            ],
            options={
                'verbose_name': 'Back Order',
                'verbose_name_plural': 'Back Orders',
                'db_table': 'back_orders',
                'ordering': ['-backorder_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, help_text='Quantity ordered', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit (quoted price)', max_digits=15)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, help_text='Quantity received so far', max_digits=15)),
                ('quantity_outstanding', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Still to be received', max_digits=15)),
                ('line_total_exclusive', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Line total (exclusive VAT)', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='VAT amount', max_digits=15)),
                ('line_total_inclusive', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Line total (inclusive VAT)', max_digits=15)),
                ('is_complete', models.BooleanField(default=False, editable=False, help_text='Fully received')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.purchaseorder')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='stock_control.stockitem')),
                ('tax_code', models.ForeignKey(help_text='VAT code', on_delete=django.db.models.deletion.PROTECT, to='settings.taxcode')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order Line Item',
                'verbose_name_plural': 'Purchase Order Line Items',
                'db_table': 'purchase_order_line_items',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='BackOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('quantity_backordered', models.DecimalField(decimal_places=2, help_text='Quantity on back order', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_fulfilled', models.DecimalField(decimal_places=2, default=0, help_text='Quantity fulfilled so far', max_digits=15)),
                ('quantity_outstanding', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Still outstanding', max_digits=15)),
                ('unit_selling_price', models.DecimalField(decimal_places=2, help_text='Selling price promised to customer', max_digits=15)),
                ('line_value', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('is_complete', models.BooleanField(default=False, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('back_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.backorder')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backorder_lines', to='stock_control.stockitem')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Back Order Line Item',
                'verbose_name_plural': 'Back Order Line Items',
                'db_table': 'back_order_line_items',
                'ordering': ['line_number'],
                'unique_together': {('back_order', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='purchase_or_po_numb_656941_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='purchase_or_supplie_d5a634_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_5ac239_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_date'], name='purchase_or_po_date_ad988d_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['backorder_number'], name='back_orders_backord_914588_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['debtor'], name='back_orders_debtor__87b729_idx'),
        ),
        migrations.AddIndex(
            model_name='backorder',
            index=models.Index(fields=['status'], name='back_orders_status_aaedce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderlineitem',
            unique_together={('purchase_order', 'line_number')},
        ),
    ]
