# Generated by Django 5.2.7 on 2026-02-05 06:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors', '0002_initial'),
        ('stock_control', '0002_contractpricing_futurepricing_onetouchlookupkey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_date', models.DateField(help_text='Expected delivery date')),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('FULLY_RECEIVED', 'Fully Received'), ('CANCELLED', 'Cancelled')], default='OUTSTANDING', max_length=20)),
                ('pricing_method', models.CharField(choices=[('COST', 'At Cost Price'), ('RETAIL', 'At Retail Price')], default='COST', help_text='Price items at cost or retail', max_length=10)),
                ('total_quantity_ordered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_quantity_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_value_exclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value_inclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_value_exclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_value_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_value_inclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_back_order', models.BooleanField(default=False, help_text='Created from delivery variance')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('parent_order', models.ForeignKey(blank=True, help_text='Original order if this is a back order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='back_orders', to='purchase_orders.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='creditors.creditor')),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date', '-order_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_outstanding', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_code', models.IntegerField(default=1)),
                ('total_exclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_inclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_exclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_inclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_on_hand_at_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_sales_at_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_fully_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.purchaseorder')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='stock_control.stockitem')),
            ],
            options={
                'db_table': 'purchase_order_lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(help_text="Supplier's invoice number", max_length=50)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_value_exclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value_inclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_variance', models.BooleanField(default=False)),
                ('variance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creditor_grn', models.ForeignKey(blank=True, help_text='Link to Goods Received Note for accounting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_receipts', to='creditors.goodsreceivednote')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchase_orders.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_receipts',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(help_text='Reason for back order (short delivery, etc)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('back_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='back_order_info', to='purchase_orders.purchaseorder')),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_back_orders', to='purchase_orders.purchaseorder')),
                ('triggering_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_orders.purchaseorderreceipt')),
            ],
            options={
                'db_table': 'back_orders',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('actual_unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_exclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_inclusive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('has_cost_variance', models.BooleanField(default=False)),
                ('cost_variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchase_orders.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.purchaseorderreceipt')),
            ],
            options={
                'db_table': 'purchase_order_receipt_lines',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_delivery_days', models.IntegerField(default=7, help_text='Days from order to delivery')),
                ('pricing_method', models.CharField(choices=[('COST', 'At Cost Price'), ('RETAIL', 'At Retail Price')], default='COST', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_templates', to='creditors.creditor')),
            ],
            options={
                'db_table': 'purchase_order_templates',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('default_quantity', models.DecimalField(decimal_places=2, help_text='Default quantity to order', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_template_lines', to='stock_control.stockitem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.purchaseordertemplate')),
            ],
            options={
                'db_table': 'purchase_order_template_lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purchase_or_supplie_8a71bd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['delivery_date'], name='purchase_or_deliver_4bacdd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_5ac239_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['stock_item'], name='purchase_or_stock_i_3a8584_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['is_fully_received'], name='purchase_or_is_full_d62b49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderline',
            unique_together={('purchase_order', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderreceipt',
            index=models.Index(fields=['purchase_order', 'receipt_date'], name='purchase_or_purchas_dfc123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseordertemplateline',
            unique_together={('template', 'line_number')},
        ),
    ]
