# Generated by Django 5.2.7 on 2026-02-13 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        ('stock_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceipt',
            name='creditor_grn',
            field=models.ForeignKey(blank=True, help_text='Link to Goods Received Note for accounting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_receipts', to='creditors.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchase_orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='backorder',
            name='triggering_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_orders.purchaseorderreceipt'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceiptline',
            name='purchase_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchase_orders.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchaseorderreceiptline',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.purchaseorderreceipt'),
        ),
        migrations.AddField(
            model_name='purchaseordertemplate',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_templates', to='creditors.creditor'),
        ),
        migrations.AddField(
            model_name='purchaseordertemplateline',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_template_lines', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='purchaseordertemplateline',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase_orders.purchaseordertemplate'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='purchase_or_supplie_8a71bd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['delivery_date'], name='purchase_or_deliver_4bacdd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_5ac239_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['stock_code'], name='purchase_or_stock_c_dc1be0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['is_fully_received'], name='purchase_or_is_full_d62b49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderline',
            unique_together={('purchase_order', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorderreceipt',
            index=models.Index(fields=['purchase_order', 'receipt_date'], name='purchase_or_purchas_dfc123_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseordertemplateline',
            unique_together={('template', 'line_number')},
        ),
    ]
