# Generated by Django 5.2.7 on 2026-02-05 09:19

import apps.cash_book.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_date', models.DateField(db_index=True, unique=True)),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_receipts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('banked_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('counted_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes_200', models.IntegerField(default=0)),
                ('notes_100', models.IntegerField(default=0)),
                ('notes_50', models.IntegerField(default=0)),
                ('notes_20', models.IntegerField(default=0)),
                ('notes_10', models.IntegerField(default=0)),
                ('coins_5', models.IntegerField(default=0)),
                ('coins_2', models.IntegerField(default=0)),
                ('coins_1', models.IntegerField(default=0)),
                ('coins_050', models.IntegerField(default=0)),
                ('coins_020', models.IntegerField(default=0)),
                ('coins_010', models.IntegerField(default=0)),
                ('coins_005', models.IntegerField(default=0)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('variance_notes', models.TextField(blank=True)),
                ('is_balanced', models.BooleanField(default=False)),
                ('counted_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cash Float',
                'db_table': 'cash_floats',
                'ordering': ['-float_date'],
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('reconciliation_date', models.DateField()),
                ('bank_account_number', models.CharField(max_length=50)),
                ('statement_date', models.DateField()),
                ('statement_number', models.CharField(blank=True, max_length=50)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance_per_statement', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance_per_books', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_cheques', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_errors', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('book_errors', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REVIEWED', 'Reviewed')], default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'bank_reconciliations',
                'ordering': ['-reconciliation_date', '-reconciliation_number'],
                'indexes': [models.Index(fields=['bank_account_number', '-reconciliation_date'], name='bank_reconc_bank_ac_de6575_idx'), models.Index(fields=['status'], name='bank_reconc_status_a73659_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashBookTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Cash Receipt'), ('PAYMENT', 'Cash Payment'), ('DEPOSIT', 'Bank Deposit'), ('WITHDRAWAL', 'Bank Withdrawal'), ('TRANSFER', 'Bank Transfer'), ('BANK_CHARGE', 'Bank Charge'), ('INTEREST', 'Interest Received'), ('OTHER_INCOME', 'Other Income'), ('OTHER_EXPENSE', 'Other Expense')], max_length=20)),
                ('transaction_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash on Hand'), ('BANK', 'Bank Account')], default='CASH', max_length=10)),
                ('bank_account_number', models.CharField(blank=True, help_text='For bank transactions', max_length=50, validators=[apps.cash_book.validators.validate_bank_account_number])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[apps.cash_book.validators.validate_positive_amount])),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('running_balance_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('running_balance_bank', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('archive_month', models.DateField(blank=True, null=True)),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cash_book.bankreconciliation')),
            ],
            options={
                'db_table': 'cashbook_transactions',
                'ordering': ['-transaction_date', '-transaction_number'],
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(max_length=50)),
                ('to_account', models.CharField(max_length=50)),
                ('transfer_reference', models.CharField(blank=True, max_length=100)),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer', to='cash_book.cashbooktransaction')),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'db_table': 'bank_transfers',
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('OUTSTANDING_DEPOSIT', 'Outstanding Deposit'), ('OUTSTANDING_CHEQUE', 'Outstanding Cheque'), ('BANK_ERROR', 'Bank Error'), ('BOOK_ERROR', 'Book Error'), ('UNRECORDED_BANK', 'Unrecorded Bank Transaction'), ('UNRECORDED_BOOK', 'Unrecorded Book Transaction')], max_length=30)),
                ('manual_date', models.DateField(blank=True, null=True)),
                ('manual_reference', models.CharField(blank=True, max_length=100)),
                ('manual_description', models.CharField(blank=True, max_length=200)),
                ('manual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cash_book.bankreconciliation')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_items', to='cash_book.cashbooktransaction')),
            ],
            options={
                'db_table': 'bank_reconciliation_items',
                'ordering': ['reconciliation', 'item_type'],
            },
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_slip_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cheque_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes_200', models.IntegerField(default=0)),
                ('notes_100', models.IntegerField(default=0)),
                ('notes_50', models.IntegerField(default=0)),
                ('notes_20', models.IntegerField(default=0)),
                ('notes_10', models.IntegerField(default=0)),
                ('coins_5', models.IntegerField(default=0)),
                ('coins_2', models.IntegerField(default=0)),
                ('coins_1', models.IntegerField(default=0)),
                ('coins_050', models.IntegerField(default=0, verbose_name='50c coins')),
                ('coins_020', models.IntegerField(default=0, verbose_name='20c coins')),
                ('coins_010', models.IntegerField(default=0, verbose_name='10c coins')),
                ('coins_005', models.IntegerField(default=0, verbose_name='5c coins')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposit', to='cash_book.cashbooktransaction')),
            ],
            options={
                'verbose_name': 'Bank Deposit',
                'db_table': 'bank_deposits',
            },
        ),
        migrations.CreateModel(
            name='BankCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('MONTHLY_FEE', 'Monthly Account Fee'), ('TRANSACTION_FEE', 'Transaction Fee'), ('ATM_FEE', 'ATM Fee'), ('OVERDRAFT', 'Overdraft Charge'), ('CARD_FEE', 'Card Fee'), ('OTHER', 'Other Charge')], max_length=100)),
                ('statement_reference', models.CharField(blank=True, max_length=100)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_charge', to='cash_book.cashbooktransaction')),
            ],
            options={
                'verbose_name': 'Bank Charge',
                'db_table': 'bank_charges',
            },
        ),
        migrations.CreateModel(
            name='CashWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_slip_number', models.CharField(blank=True, max_length=50)),
                ('withdrawn_by', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_withdrawal', to='cash_book.cashbooktransaction')),
            ],
            options={
                'verbose_name': 'Cash Withdrawal',
                'db_table': 'cash_withdrawals',
            },
        ),
        migrations.CreateModel(
            name='InterestReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_period_start', models.DateField()),
                ('interest_period_end', models.DateField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_received', to='cash_book.cashbooktransaction')),
            ],
            options={
                'verbose_name': 'Interest Received',
                'db_table': 'interest_received',
            },
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vat_inclusive', models.BooleanField(default=True)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_code', models.IntegerField(default=1)),
                ('paid_from', models.CharField(choices=[('CASH', 'Cash Till'), ('BANK', 'Bank Account')], default='CASH', max_length=20)),
                ('petty_cash_slip_number', models.CharField(blank=True, max_length=20)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.expensecategory')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_expense', to='cash_book.cashbooktransaction')),
            ],
            options={
                'verbose_name': 'Other Expense',
                'db_table': 'other_expenses',
            },
        ),
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vat_inclusive', models.BooleanField(default=True)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_code', models.IntegerField(default=1, help_text='1=14%, 2=0%')),
                ('paid_into', models.CharField(choices=[('CASH', 'Cash Till'), ('BANK', 'Bank Account')], default='CASH', max_length=20)),
                ('income_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.incomecategory')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_income', to='cash_book.cashbooktransaction')),
            ],
            options={
                'verbose_name': 'Other Income',
                'verbose_name_plural': 'Other Income',
                'db_table': 'other_income',
            },
        ),
        migrations.AddIndex(
            model_name='cashbooktransaction',
            index=models.Index(fields=['transaction_type', '-transaction_date'], name='cashbook_tr_transac_706480_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbooktransaction',
            index=models.Index(fields=['transaction_number'], name='cashbook_tr_transac_116d80_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbooktransaction',
            index=models.Index(fields=['is_reconciled'], name='cashbook_tr_is_reco_e73466_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbooktransaction',
            index=models.Index(fields=['is_archived', 'archive_month'], name='cashbook_tr_is_arch_c0abe9_idx'),
        ),
    ]
