# Generated by Django 5.2.7 on 2026-01-30 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_book', '0001_initial'),
        ('debtors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postdatedchequeregister',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdc_register', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='postdatedchequeregister',
            name='pdc',
            field=models.ForeignKey(help_text="Link to debtor's post-dated cheque", on_delete=django.db.models.deletion.CASCADE, related_name='register_entries', to='debtors.postdatedcheque'),
        ),
        migrations.AddField(
            model_name='postdatedchequeregister',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpresentedcheque',
            name='cleared_in_reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_cheques', to='cash_book.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='unpresentedcheque',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpresentedcheque',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unpresentedcheque',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='otherexpenselineitem',
            unique_together={('expense_transaction', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='otherincomelineitem',
            unique_together={('income_transaction', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='postdatedchequeregister',
            index=models.Index(fields=['banking_date'], name='pdc_registe_banking_89d380_idx'),
        ),
        migrations.AddIndex(
            model_name='postdatedchequeregister',
            index=models.Index(fields=['status'], name='pdc_registe_status_d1b958_idx'),
        ),
        migrations.AddIndex(
            model_name='postdatedchequeregister',
            index=models.Index(fields=['is_banked'], name='pdc_registe_is_bank_68da29_idx'),
        ),
        migrations.AddIndex(
            model_name='unpresentedcheque',
            index=models.Index(fields=['is_presented'], name='unpresented_is_pres_094001_idx'),
        ),
        migrations.AddIndex(
            model_name='unpresentedcheque',
            index=models.Index(fields=['cheque_date'], name='unpresented_cheque__a84d25_idx'),
        ),
    ]
