# Generated by Django 5.2.7 on 2026-07-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cash_book", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTillTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trading_date",
                    models.DateField(help_text="Parsed from cf<DDMMYY>.dbf filename"),
                ),
                (
                    "source",
                    models.CharField(blank=True, help_text="SOURCE", max_length=2),
                ),
                (
                    "cash_total",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="CASHDAY", max_digits=12
                    ),
                ),
                (
                    "cheque_total",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="CHEQDAY", max_digits=12
                    ),
                ),
                (
                    "card_total",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="CARDDAY", max_digits=12
                    ),
                ),
                (
                    "invoice_total",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="INVTOT", max_digits=12
                    ),
                ),
                (
                    "credit_note_total",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="CNOTETOT", max_digits=12
                    ),
                ),
                (
                    "reconciliation_account_total",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="RECONACC", max_digits=12
                    ),
                ),
                (
                    "output_vat",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="OUTVAT", max_digits=12
                    ),
                ),
                (
                    "input_vat",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="INVAT", max_digits=12
                    ),
                ),
                (
                    "transaction_time",
                    models.CharField(blank=True, help_text="TIME", max_length=5),
                ),
                (
                    "transaction_number",
                    models.PositiveIntegerField(default=0, help_text="TRANO"),
                ),
                (
                    "transaction_type",
                    models.CharField(blank=True, help_text="TYPE", max_length=2),
                ),
                (
                    "change_given",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="CHANGE", max_digits=12
                    ),
                ),
                (
                    "laybye_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="LAYBYE", max_digits=12
                    ),
                ),
                (
                    "comments",
                    models.CharField(blank=True, help_text="COMMENTS", max_length=75),
                ),
                (
                    "speedpoint_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="SPEEDPOINT",
                        max_digits=12,
                    ),
                ),
                (
                    "adjustment",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="ADJUST", max_digits=10
                    ),
                ),
                (
                    "captured_by_user",
                    models.CharField(blank=True, help_text="USER", max_length=25),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "daily_till_transactions",
                "ordering": ["trading_date", "transaction_number"],
                "indexes": [
                    models.Index(
                        fields=["trading_date"], name="daily_till__trading_7b31aa_idx"
                    )
                ],
                "unique_together": {("trading_date", "transaction_number", "source")},
            },
        ),
    ]
