# Generated by Django 5.2.7 on 2026-02-04 19:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors', '0002_initial'),
        ('debtors', '0001_initial'),
        ('settings', '0001_initial'),
        ('stock_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_method', models.CharField(choices=[('ACTUAL', 'Actual Price'), ('COST_MARKUP', 'Cost + Markup%')], max_length=20)),
                ('contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_fixed_pricing', models.BooleanField(default=False, help_text='Prevent POS from changing price')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contract_pricing',
            },
        ),
        migrations.CreateModel(
            name='FuturePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_cost_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('future_selling_price_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('future_selling_price_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('future_selling_price_3', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('future_markup_1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('future_markup_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('future_markup_3', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_date', models.DateField()),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'future_pricing',
                'ordering': ['effective_date'],
            },
        ),
        migrations.CreateModel(
            name='OneTouchLookupKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_character', models.CharField(help_text='Single uppercase letter', max_length=1, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'one_touch_lookup_keys',
            },
        ),
        migrations.CreateModel(
            name='PackBundle',
            fields=[
                ('stock_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pack_bundle', serialize=False, to='stock_control.stockitem')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pack_bundles',
            },
        ),
        migrations.CreateModel(
            name='PackBundleIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cost_at_creation', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pack_bundle_ingredients',
            },
        ),
        migrations.CreateModel(
            name='ShrinkWrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_bulk', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shrink_wraps',
            },
        ),
        migrations.CreateModel(
            name='StockMonthlyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('quantity_sold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value_sold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_monthly_statistics',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOMING', 'Incoming Stock'), ('RETURN', 'Stock Return'), ('SALE', 'Sale'), ('SALE_RETURN', 'Sale Return'), ('ADJUSTMENT', 'Stock Adjustment'), ('STOCK_TAKE', 'Stock Take'), ('MANUFACTURE', 'Manufactured from Bundle'), ('BUNDLE_USE', 'Used in Bundle'), ('BULK_ISSUE', 'Issued from Bulk'), ('LAYBYE_IN', 'Laybye Issue'), ('LAYBYE_OUT', 'Laybye Return'), ('JOB_IN', 'Job Card Issue'), ('JOB_OUT', 'Job Card Return'), ('RFC_IN', 'RFC Issue'), ('RFC_OUT', 'RFC Return')], max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_number', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity_in', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_out', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('station_number', models.IntegerField(blank=True, help_text='Station number for stock take updates', null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stock_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bundleingredient',
            name='bundle',
        ),
        migrations.AlterUniqueTogether(
            name='bundleingredient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bundleingredient',
            name='ingredient_item',
        ),
        migrations.RemoveField(
            model_name='contractprice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contractprice',
            name='debtor',
        ),
        migrations.RemoveField(
            model_name='contractprice',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='contractpriceitem',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='contractpriceitem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='contractpriceitem',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='contractpriceitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='futureprice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='futureprice',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='futureprice',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='shrinkwraprelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shrinkwraprelationship',
            name='bulk_pack',
        ),
        migrations.RemoveField(
            model_name='shrinkwraprelationship',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shrinkwraprelationship',
            name='shrink_pack',
        ),
        migrations.RemoveField(
            model_name='shrinkwraprelationship',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='specialdeal',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['stock_code']},
        ),
        migrations.AlterModelOptions(
            name='stocktake',
            options={'ordering': ['-stock_take_date']},
        ),
        migrations.AlterModelOptions(
            name='stocktakeitem',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='stock_items_stock_c_c49d8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='stock_items_supplie_544319_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockitem',
            name='stock_items_is_acti_025493_idx',
        ),
        migrations.RenameField(
            model_name='stocktakeitem',
            old_name='stocktake',
            new_name='stock_take',
        ),
        migrations.RemoveField(
            model_name='specialdeal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specialdeal',
            name='deal_type',
        ),
        migrations.RemoveField(
            model_name='specialdeal',
            name='department',
        ),
        migrations.RemoveField(
            model_name='specialdeal',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='average_cost_price',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='deactivated_at',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='deactivated_by',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='gross_profit_mtd',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='gross_profit_ytd',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='last_cost_price',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='markup_percent_1',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='markup_percent_2',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='markup_percent_3',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity_on_layby',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity_on_sales_order',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='quantity_rfc',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='sales_quantity_mtd',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='sales_quantity_ytd',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='sales_value_mtd',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='sales_value_ytd',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='reset_negative_to_zero',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='stocktake_date',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='update_from_datetime',
        ),
        migrations.RemoveField(
            model_name='stocktake',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeitem',
            unique_together={('stock_take', 'stock_item')},
        ),
        migrations.AddField(
            model_name='specialdeal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='bin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='markup_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='markup_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='markup_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='quantity_counted',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Used during stock take', max_digits=10),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sales_mtd_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sales_mtd_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sales_ytd_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sales_ytd_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='is_after_trading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='reset_negatives_to_zero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='stock_take_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='trading_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='cost_price_at_count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='count_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='is_counted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=2, default=1, help_text='System quantity before count', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='variance_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktakeitem',
            name='variance_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='specialdeal',
            name='special_cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='specialdeal',
            name='special_selling_price_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='specialdeal',
            name='special_selling_price_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='specialdeal',
            name='special_selling_price_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='specialdeal',
            name='stock_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='special_deals', to='stock_control.stockitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='allow_negative_quantities',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='date_last_purchased',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='date_last_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='default_selling_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='settings.salesdepartment'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='maximum_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity_on_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='reorder_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='selling_price_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='selling_price_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='selling_price_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='stock_code',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='creditors.creditor'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='supplier_code',
            field=models.CharField(blank=True, help_text="Supplier's stock code", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='settings.taxcode'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='set_uncounted_to_zero',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('UPDATED', 'Updated')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktake',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='quantity_counted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocktakeitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_take_items', to='stock_control.stockitem'),
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['supplier', 'supplier_code'], name='stock_items_supplie_96c2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktakeitem',
            index=models.Index(fields=['stock_take', 'is_counted'], name='stock_take__stock_t_9da901_idx'),
        ),
        migrations.AddField(
            model_name='contractpricing',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_prices', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='contractpricing',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_prices', to='settings.salesdepartment'),
        ),
        migrations.AddField(
            model_name='contractpricing',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_prices', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='contractpricing',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_prices', to='creditors.creditor'),
        ),
        migrations.AddField(
            model_name='futurepricing',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_prices', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='onetouchlookupkey',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookup_keys', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='packbundleingredient',
            name='ingredient_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='packbundleingredient',
            name='pack_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='stock_control.packbundle'),
        ),
        migrations.AddField(
            model_name='shrinkwrap',
            name='bulk_pack_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrink_bulks', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='shrinkwrap',
            name='shrink_pack_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrink_items', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='stockmonthlystatistic',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stock_control.stockitem'),
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
        migrations.DeleteModel(
            name='BundleIngredient',
        ),
        migrations.DeleteModel(
            name='ContractPrice',
        ),
        migrations.DeleteModel(
            name='ContractPriceItem',
        ),
        migrations.DeleteModel(
            name='FuturePrice',
        ),
        migrations.DeleteModel(
            name='ShrinkWrapRelationship',
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.RemoveField(
            model_name='stocktakeitem',
            name='quantity_system',
        ),
        migrations.RemoveField(
            model_name='stocktakeitem',
            name='quantity_variance',
        ),
        migrations.RemoveField(
            model_name='stocktakeitem',
            name='value_variance',
        ),
        migrations.AddIndex(
            model_name='contractpricing',
            index=models.Index(fields=['debtor', 'stock_item'], name='contract_pr_debtor__2085eb_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpricing',
            index=models.Index(fields=['debtor', 'department'], name='contract_pr_debtor__84b5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpricing',
            index=models.Index(fields=['debtor', 'supplier'], name='contract_pr_debtor__63cf2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packbundleingredient',
            unique_together={('pack_bundle', 'ingredient_stock')},
        ),
        migrations.AlterUniqueTogether(
            name='shrinkwrap',
            unique_together={('bulk_pack_code', 'shrink_pack_code')},
        ),
        migrations.AlterUniqueTogether(
            name='stockmonthlystatistic',
            unique_together={('stock_item', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['stock_item', 'transaction_date'], name='stock_trans_stock_i_7a40d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type'], name='stock_trans_transac_b2b788_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_date'], name='stock_trans_transac_9087d2_idx'),
        ),
    ]
