# Generated by Django 5.2.7 on 2026-02-21 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creditors", "0003_remove_rfclineitem_original_transaction_time_and_more"),
        ("debtors", "0001_initial"),
        ("settings", "0001_initial"),
        ("stock_control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovementLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_date",
                    models.DateField(help_text="DATE - Date of movement"),
                ),
                (
                    "movement_time",
                    models.TimeField(
                        blank=True, help_text="TIME - Time of movement", null=True
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        help_text="TYPE - Movement type code (e.g. SI, SO, SR)",
                        max_length=2,
                    ),
                ),
                (
                    "transaction_number",
                    models.IntegerField(
                        blank=True,
                        help_text="TRANO - Linked transaction number",
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="DETAILS - Description or reference",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "quantity_in",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="QTYIN - Quantity received",
                        max_digits=14,
                    ),
                ),
                (
                    "quantity_out",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="QTYOUT - Quantity issued",
                        max_digits=14,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="BALANCE - Running stock balance",
                        max_digits=14,
                    ),
                ),
                (
                    "brought_forward",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="BFWD - Brought-forward value",
                        max_digits=12,
                    ),
                ),
                (
                    "per_unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="PERUNIT - Cost per unit at time of movement",
                        max_digits=12,
                    ),
                ),
                (
                    "supplier_details",
                    models.CharField(
                        blank=True,
                        help_text="SUPDETAILS - Supplier reference or details",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "record_reference",
                    models.CharField(
                        blank=True,
                        help_text="RECORD - Source record reference",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stock_movement_ledger",
                "ordering": ["stock_item", "movement_date", "movement_time"],
            },
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="reference",
        ),
        migrations.AddField(
            model_name="stockitem",
            name="job_card_bfwd_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="JCBFWDVAL - Job card brought-forward value",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="kvi_flag",
            field=models.CharField(
                blank=True,
                help_text="KVI - Known Value Item flag",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="laybye_bfwd_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="LBBFWDVAL - Laybye brought-forward value",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="pack_code",
            field=models.CharField(
                blank=True,
                help_text="PACK - Pack or bundle group code",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="rfc_bfwd_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="RFBFWDVAL - RFC (Repair/Field Call) brought-forward value",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="branch_code",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="branchstock",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="branchstock",
            name="quantity_allocated",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="branchstock",
            name="reorder_level",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="branchstock",
            name="reorder_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="branchtransfer",
            name="transfer_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="branchtransferinvoice",
            name="invoice_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="branchtransferitem",
            name="variance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="futurepricing",
            name="future_cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Anticipated cost price at effective date (app-managed, not in legacy DBF)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="grouporder",
            name="group_order_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="specialdeal",
            name="special_cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost price applicable during the special period (app-managed, not in legacy DBF)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="average_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="bin_number",
            field=models.IntegerField(
                blank=True, help_text="BIN - Bin/shelf location number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="description",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="markup_1",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="markup_2",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="markup_3",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="maximum_discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="quantity_allocated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="QTYBYSTOCK - Quantity allocated to batches/lots",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="quantity_on_order",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="QTYPORD - Quantity on purchase order",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="supplier_code",
            field=models.CharField(
                blank=True, help_text="Supplier's stock code", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="cost_price_at_count",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stocktakeitem",
            name="quantity_on_hand",
            field=models.DecimalField(
                decimal_places=4,
                help_text="System quantity before count",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="comments",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="debtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_transactions",
                to="debtors.debtor",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_transactions",
                to="settings.salesdepartment",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="quantity_balance",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="quantity_in",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="quantity_out",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="station_number",
            field=models.IntegerField(
                blank=True,
                help_text="SOURCE - Station/POS terminal or source number",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_transactions",
                to="creditors.creditor",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="tax_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_transactions",
                to="settings.taxcode",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_number",
            field=models.IntegerField(
                blank=True, help_text="TRANO - Transaction reference number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["transaction_number"], name="stock_trans_transac_3517d6_idx"
            ),
        ),
        migrations.AddField(
            model_name="stockmovementledger",
            name="stock_item",
            field=models.ForeignKey(
                help_text="Stock item this ledger entry belongs to",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movement_ledger",
                to="stock_control.stockitem",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovementledger",
            index=models.Index(
                fields=["stock_item", "movement_date"],
                name="stock_movem_stock_i_fdfedb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovementledger",
            index=models.Index(
                fields=["movement_type"], name="stock_movem_movemen_d18ab9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovementledger",
            index=models.Index(
                fields=["transaction_number"], name="stock_movem_transac_4f879b_idx"
            ),
        ),
    ]
