# Generated by Django 5.2.7 on 2026-07-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_systemconfiguration_day_end_day_of_week_and_more'),
        ('stock_control', '0005_add_barcode_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTimeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name_legacy', models.CharField(blank=True, help_text='DEPTNAME', max_length=20)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='DAYOFWEEK')),
                ('start_time', models.TimeField(help_text='START_TIME')),
                ('end_time', models.TimeField(help_text='END_TIME')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='DISCOUNT', max_digits=5)),
                ('discount_type', models.CharField(blank=True, help_text='TYPE', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='DEPT', on_delete=django.db.models.deletion.CASCADE, related_name='time_discounts', to='settings.salesdepartment')),
            ],
            options={
                'db_table': 'department_time_discounts',
                'ordering': ['department', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SerializedStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='SERIALNO', max_length=20, unique=True)),
                ('item_detail', models.CharField(blank=True, help_text='ITEMDETAIL', max_length=30)),
                ('transaction_date', models.DateField(blank=True, help_text='DATE', null=True)),
                ('transaction_type', models.CharField(blank=True, help_text='TRANSTYPE', max_length=2)),
                ('transaction_number', models.PositiveIntegerField(blank=True, help_text='TRANSNO', null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='VALUE', max_digits=12)),
                ('warranty_period_months', models.PositiveIntegerField(blank=True, help_text='WARRANTPER', null=True)),
                ('comment1', models.CharField(blank=True, help_text='COMMENT1', max_length=30)),
                ('comment2', models.CharField(blank=True, help_text='COMMENT2', max_length=30)),
                ('comment3', models.CharField(blank=True, help_text='COMMENT3', max_length=30)),
                ('comment4', models.CharField(blank=True, help_text='COMMENT4', max_length=30)),
                ('customer_name', models.CharField(blank=True, help_text='NAME', max_length=40)),
                ('address_line1', models.CharField(blank=True, help_text='ADD1', max_length=25)),
                ('address_line2', models.CharField(blank=True, help_text='ADD2', max_length=25)),
                ('address_line3', models.CharField(blank=True, help_text='ADD3', max_length=25)),
                ('telephone', models.CharField(blank=True, help_text='TEL', max_length=15)),
                ('email', models.CharField(blank=True, help_text='EMAIL', max_length=50)),
                ('is_stolen', models.BooleanField(default=False, help_text='STOLEN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_item', models.ForeignKey(blank=True, help_text='CODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='stock_control.stockitem')),
            ],
            options={
                'db_table': 'serialized_stock_items',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='StagedPriceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, help_text='SUPNAME', max_length=30)),
                ('department_name', models.CharField(blank=True, help_text='DEPARTMENT', max_length=20)),
                ('description', models.CharField(blank=True, help_text='DESCRIP', max_length=30)),
                ('unit_of_measure', models.CharField(blank=True, help_text='UNITOFMEAS', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='COST', max_digits=12)),
                ('sell_price_1', models.DecimalField(decimal_places=2, default=0, help_text='SELL1', max_digits=12)),
                ('sell_price_2', models.DecimalField(decimal_places=2, default=0, help_text='SELL2', max_digits=12)),
                ('sell_price_3', models.DecimalField(decimal_places=2, default=0, help_text='SELL3', max_digits=12)),
                ('effective_date', models.DateField(blank=True, help_text='EFFECTDATE', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_item', models.ForeignKey(blank=True, help_text='STOCKCODE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_price_updates', to='stock_control.stockitem')),
            ],
            options={
                'db_table': 'staged_price_updates',
                'ordering': ['effective_date'],
            },
        ),
        migrations.CreateModel(
            name='StockPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='STARTDATE')),
                ('end_date', models.DateField(help_text='ENDDATE')),
                ('basis', models.CharField(blank=True, help_text='BASIS', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='AMOUNT', max_digits=12)),
                ('message_line1', models.CharField(blank=True, help_text='MESSAGE1', max_length=40)),
                ('message_line2', models.CharField(blank=True, help_text='MESSAGE2', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='DEPT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_promotions', to='settings.salesdepartment')),
                ('stock_item', models.ForeignKey(help_text='CODE', on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='stock_control.stockitem')),
            ],
            options={
                'db_table': 'stock_promotions',
                'ordering': ['-start_date'],
            },
        ),
    ]
