# Generated by Django 5.2.7 on 2026-08-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_control", "0007_stagedpriceupdate_stock_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractpricing",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="Contract price valid from (unbounded if blank)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractpricing",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Contract price valid until (unbounded if blank)",
                null=True,
            ),
        ),
    ]
