# Generated by Django 5.2.7 on 2026-08-29 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_control", "0008_contractpricing_valid_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branchtransferinvoice",
            name="invoice_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="grouporder",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="stocktake",
            name="stock_take_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
