# Generated by Django 5.2.7 on 2026-08-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rentaltransaction',
            new_name='rentals_ren_debtor__d8e63e_idx',
            old_name='rentals_ren_debtor__1a6b4a_idx',
        ),
        migrations.RenameIndex(
            model_name='rentaltransaction',
            new_name='rentals_ren_status_d74363_idx',
            old_name='rentals_ren_status_9d5e21_idx',
        ),
    ]
