# Generated by Django 5.2.7 on 2026-02-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_users', '0004_shopuser_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin - Full tenant access'), ('MANAGER', 'Manager - Can manage shop users'), ('USER', 'User - Basic access')], default='USER', max_length=20),
        ),
    ]
