# Generated by Django 5.2.7 on 2026-02-20 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GLParam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "startper",
                    models.IntegerField(
                        default=1,
                        help_text="Start period (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "batchno",
                    models.BigIntegerField(
                        default=0,
                        help_text="Batch # (numeric, 8 digits max)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                    ),
                ),
                (
                    "curperiod",
                    models.IntegerField(
                        default=1,
                        help_text="Current period (1-13)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ],
                    ),
                ),
                (
                    "adjusted",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        default="N",
                        help_text="Has database been adjusted (Y/N)",
                        max_length=1,
                    ),
                ),
                (
                    "currentyr",
                    models.IntegerField(
                        default=2026,
                        help_text="Current Year (4 digits)",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Parameter",
                "verbose_name_plural": "GL Parameters",
            },
        ),
        migrations.CreateModel(
            name="GLBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accno",
                    models.BigIntegerField(
                        help_text="Account # (8 digits)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                    ),
                ),
                (
                    "batchno",
                    models.BigIntegerField(
                        help_text="Batch # (8 digits)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                    ),
                ),
                ("capturedat", models.DateField(help_text="Date captured")),
                ("date", models.DateField(help_text="Transaction date")),
                (
                    "time",
                    models.CharField(
                        blank=True, help_text="Transaction time (HH:MM)", max_length=5
                    ),
                ),
                (
                    "drorcr",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")],
                        help_text="Debit or Credit",
                        max_length=1,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("M", "Manual"),
                            ("S", "System"),
                            ("I", "Import"),
                            ("B", "Bank"),
                            ("O", "Other"),
                        ],
                        default="M",
                        help_text="Journal entry source",
                        max_length=1,
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        blank=True, help_text="Station # (2 characters)", max_length=2
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="Transaction reference", max_length=10
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True, help_text="Transaction Details", max_length=30
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Value (transaction amount)",
                        max_digits=12,
                    ),
                ),
                (
                    "postdate",
                    models.DateField(blank=True, help_text="Date posted", null=True),
                ),
                (
                    "postime",
                    models.CharField(
                        blank=True, help_text="Time posted (HH:MM)", max_length=5
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        help_text="Period to post to (1-13)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Batch Transaction",
                "verbose_name_plural": "GL Batch Transactions",
                "ordering": ["-capturedat", "batchno", "accno"],
                "indexes": [
                    models.Index(
                        fields=["batchno"], name="general_led_batchno_527c1e_idx"
                    ),
                    models.Index(
                        fields=["accno", "date"], name="general_led_accno_d81d91_idx"
                    ),
                    models.Index(
                        fields=["capturedat"], name="general_led_capture_0fe259_idx"
                    ),
                    models.Index(
                        fields=["postdate"], name="general_led_postdat_e12ebb_idx"
                    ),
                    models.Index(
                        fields=["drorcr"], name="general_led_drorcr_bda8fc_idx"
                    ),
                    models.Index(
                        fields=["source"], name="general_led_source_6ed3fd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GLMast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accno",
                    models.BigIntegerField(
                        help_text="Account Number (8 digits)",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="Account Name", max_length=30)),
                (
                    "type",
                    models.CharField(
                        choices=[("I", "Income Statement"), ("B", "Balance Sheet")],
                        help_text="Income Statement or Balance Sheet",
                        max_length=1,
                    ),
                ),
                (
                    "drorcr",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")],
                        help_text="Debit or Credit",
                        max_length=1,
                    ),
                ),
                ("repline", models.IntegerField(help_text="Report line number")),
                (
                    "balbfwd",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Balance Brought Forward",
                        max_digits=14,
                    ),
                ),
                (
                    "period1",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 1 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 2 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period3",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 3 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period4",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 4 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period5",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 5 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period6",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 6 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period7",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 7 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period8",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 8 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period9",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 9 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period10",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 10 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period11",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 11 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period12",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 12 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "period13",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Period 13 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "budget1",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 1",
                        max_digits=14,
                    ),
                ),
                (
                    "budget2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 2",
                        max_digits=14,
                    ),
                ),
                (
                    "budget3",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 3",
                        max_digits=14,
                    ),
                ),
                (
                    "budget4",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 4",
                        max_digits=14,
                    ),
                ),
                (
                    "budget5",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 5",
                        max_digits=14,
                    ),
                ),
                (
                    "budget6",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 6",
                        max_digits=14,
                    ),
                ),
                (
                    "budget7",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 7",
                        max_digits=14,
                    ),
                ),
                (
                    "budget8",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 8",
                        max_digits=14,
                    ),
                ),
                (
                    "budget9",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 9",
                        max_digits=14,
                    ),
                ),
                (
                    "budget10",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 10",
                        max_digits=14,
                    ),
                ),
                (
                    "budget11",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 11",
                        max_digits=14,
                    ),
                ),
                (
                    "budget12",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Budget Period 12",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear1",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 1 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear2",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 2 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear3",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 3 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear4",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 4 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear5",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 5 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear6",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 6 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear7",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 7 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear8",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 8 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear9",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 9 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear10",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 10 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear11",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 11 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "lastyear12",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Last Year Period 12 Balance",
                        max_digits=14,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Master Account",
                "verbose_name_plural": "GL Master Accounts",
                "ordering": ["accno"],
                "indexes": [
                    models.Index(fields=["accno"], name="general_led_accno_733e57_idx"),
                    models.Index(fields=["type"], name="general_led_type_f2cef6_idx"),
                    models.Index(
                        fields=["drorcr"], name="general_led_drorcr_92ae98_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GLRep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("I", "Income Statement"), ("B", "Balance Sheet")],
                        help_text="Income Statement or Balance Sheet",
                        max_length=1,
                    ),
                ),
                (
                    "fieldtype",
                    models.CharField(
                        choices=[
                            ("H", "Heading"),
                            ("T", "Total"),
                            ("D", "Detail"),
                            ("S", "Subtotal"),
                        ],
                        help_text="Type of heading (Heading, Total, Detail, Subtotal)",
                        max_length=1,
                    ),
                ),
                (
                    "line",
                    models.IntegerField(
                        help_text="Line # (1-9999)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "printdet",
                    models.CharField(
                        choices=[("D", "Double"), ("S", "Single"), ("N", "None")],
                        default="N",
                        help_text="Double/Single/None line format",
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Heading/Total name", max_length=30),
                ),
                (
                    "start",
                    models.IntegerField(
                        help_text="Start line #",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "endcalc",
                    models.IntegerField(
                        help_text="End line # for calculation",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Report Format",
                "verbose_name_plural": "GL Report Formats",
                "ordering": ["type", "line"],
                "indexes": [
                    models.Index(
                        fields=["type", "line"], name="general_led_type_bcb6c8_idx"
                    ),
                    models.Index(fields=["type"], name="general_led_type_5196ce_idx"),
                    models.Index(
                        fields=["fieldtype"], name="general_led_fieldty_bc62f9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GLSpread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accno",
                    models.BigIntegerField(
                        help_text="Account # (8 digits)",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                    ),
                ),
                ("name", models.CharField(help_text="Account Name", max_length=30)),
                (
                    "ytddebit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Year-to-date debit",
                        max_digits=14,
                    ),
                ),
                (
                    "ytdcredit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Year-to-date credit",
                        max_digits=14,
                    ),
                ),
                (
                    "curdebit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current period debit",
                        max_digits=14,
                    ),
                ),
                (
                    "curcredit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current period credit",
                        max_digits=14,
                    ),
                ),
                (
                    "curbuddeb",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current budget debit",
                        max_digits=14,
                    ),
                ),
                (
                    "curbudcred",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current budget credit",
                        max_digits=14,
                    ),
                ),
                (
                    "ytdbuddeb",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Year-to-date budget debit",
                        max_digits=14,
                    ),
                ),
                (
                    "ytdbudcred",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Year-to-date budget credit",
                        max_digits=14,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Spread Sheet",
                "verbose_name_plural": "GL Spread Sheets",
                "ordering": ["accno"],
                "indexes": [
                    models.Index(fields=["accno"], name="general_led_accno_979b80_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="GLStJnl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accno",
                    models.BigIntegerField(
                        help_text="Account # (8 digits)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                    ),
                ),
                (
                    "details",
                    models.CharField(help_text="Transaction details", max_length=30),
                ),
                (
                    "drorcr",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")],
                        help_text="Debit or Credit",
                        max_length=1,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Value (transaction amount)",
                        max_digits=14,
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        help_text="# of times to occur (1-9)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                    ),
                ),
                (
                    "stperiod",
                    models.IntegerField(
                        help_text="Start period (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "times",
                    models.IntegerField(
                        help_text="# of times to apply (1-999)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "timesbal",
                    models.IntegerField(
                        default=0,
                        help_text="Total of times (0-999)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "nextperiod",
                    models.IntegerField(
                        help_text="Next period (1-12)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "descriptor",
                    models.CharField(
                        blank=True, help_text="Reference descriptor", max_length=30
                    ),
                ),
                (
                    "journalno",
                    models.IntegerField(
                        help_text="Journal # (6 digits max)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Standing Journal",
                "verbose_name_plural": "GL Standing Journals",
                "ordering": ["accno", "journalno"],
                "indexes": [
                    models.Index(fields=["accno"], name="general_led_accno_891883_idx"),
                    models.Index(
                        fields=["journalno"], name="general_led_journal_53be38_idx"
                    ),
                    models.Index(
                        fields=["stperiod"], name="general_led_stperio_9328d8_idx"
                    ),
                    models.Index(
                        fields=["drorcr"], name="general_led_drorcr_0cae16_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GLTran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accno",
                    models.BigIntegerField(
                        help_text="Account Number (8 digits)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                    ),
                ),
                (
                    "batchno",
                    models.BigIntegerField(
                        help_text="Batch Number (8 digits) - groups related transactions",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999),
                        ],
                    ),
                ),
                ("date", models.DateField(help_text="Transaction date")),
                (
                    "time",
                    models.TimeField(
                        blank=True, help_text="Transaction time (HH:MM)", null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")],
                        help_text="Debit or Credit",
                        max_length=1,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("M", "Manual"),
                            ("S", "System"),
                            ("I", "Import"),
                            ("B", "Bank"),
                            ("O", "Other"),
                        ],
                        default="M",
                        help_text="Journal entry source (Manual, System, Import, Bank, Other)",
                        max_length=1,
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        blank=True, help_text="Station/Workstation number", max_length=2
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Transaction reference code/voucher number",
                        max_length=10,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="Transaction details/description",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Transaction amount", max_digits=12
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Transaction",
                "verbose_name_plural": "GL Transactions",
                "ordering": ["-date", "-time", "accno"],
                "indexes": [
                    models.Index(
                        fields=["accno", "date"], name="general_led_accno_7e8200_idx"
                    ),
                    models.Index(
                        fields=["batchno"], name="general_led_batchno_d14368_idx"
                    ),
                    models.Index(fields=["date"], name="general_led_date_4aa28b_idx"),
                    models.Index(fields=["type"], name="general_led_type_dd8c5a_idx"),
                    models.Index(
                        fields=["source"], name="general_led_source_896596_idx"
                    ),
                    models.Index(
                        fields=["reference"], name="general_led_referen_906ee4_idx"
                    ),
                ],
            },
        ),
    ]
