# Generated by Django 5.2.7 on 2026-08-30 01:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_ledger", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="glparam",
            name="retained_earnings_accno",
            field=models.BigIntegerField(
                blank=True,
                help_text="GLMast.accno that Income Statement accounts are closed against at Year End. Must be configured (a Balance Sheet, credit-normal equity account) before year_end can run.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999999),
                ],
            ),
        ),
        migrations.CreateModel(
            name="GLIntegrationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "debtors_control_accno",
                    models.BigIntegerField(
                        blank=True, help_text="Debtors Control account", null=True
                    ),
                ),
                (
                    "creditors_control_accno",
                    models.BigIntegerField(
                        blank=True, help_text="Creditors Control account", null=True
                    ),
                ),
                (
                    "bank_control_accno",
                    models.BigIntegerField(
                        blank=True, help_text="Bank Control account", null=True
                    ),
                ),
                (
                    "cash_control_accno",
                    models.BigIntegerField(
                        blank=True, help_text="Cash Control account", null=True
                    ),
                ),
                (
                    "sales_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Sales / Revenue control account",
                        null=True,
                    ),
                ),
                (
                    "vat_output_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="VAT Output (payable) control account",
                        null=True,
                    ),
                ),
                (
                    "vat_input_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="VAT Input (receivable) control account",
                        null=True,
                    ),
                ),
                (
                    "stock_control_accno",
                    models.BigIntegerField(
                        blank=True, help_text="Stock Control account", null=True
                    ),
                ),
                (
                    "stock_shrinkage_expense_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Stock shrinkage/loss expense account (stock take net losses)",
                        null=True,
                    ),
                ),
                (
                    "stock_gain_income_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Stock gain income account (stock take net gains)",
                        null=True,
                    ),
                ),
                (
                    "debtors_interest_income_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Interest charged to debtors — income account",
                        null=True,
                    ),
                ),
                (
                    "debtors_suspense_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Offsetting account for manual debtor journal adjustments (JD/JC)",
                        null=True,
                    ),
                ),
                (
                    "creditors_discount_received_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Discount received on creditor payments (optional split)",
                        null=True,
                    ),
                ),
                (
                    "creditors_suspense_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Offsetting account for manual creditor journal adjustments",
                        null=True,
                    ),
                ),
                (
                    "cashbook_default_income_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Fallback income account for cash book transactions with no category-level GL mapping",
                        null=True,
                    ),
                ),
                (
                    "cashbook_default_expense_accno",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Fallback expense account for cash book transactions with no category-level GL mapping",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Integration Settings",
                "verbose_name_plural": "GL Integration Settings",
            },
        ),
        migrations.CreateModel(
            name="GLIntegrationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_app",
                    models.CharField(
                        choices=[
                            ("debtors", "Debtors"),
                            ("creditors", "Creditors"),
                            ("stock_control", "Stock Control"),
                            ("cash_book", "Cash Book"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_model", models.CharField(max_length=50)),
                ("source_pk", models.BigIntegerField()),
                (
                    "gl_batchno",
                    models.BigIntegerField(
                        help_text="GLTran.batchno this record posted to"
                    ),
                ),
                ("transferred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Integration Log",
                "verbose_name_plural": "GL Integration Log",
                "indexes": [
                    models.Index(
                        fields=["source_app", "source_model"],
                        name="general_led_source__f58e78_idx",
                    ),
                    models.Index(
                        fields=["gl_batchno"], name="general_led_gl_batc_2fdcb2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_app", "source_model", "source_pk"),
                        name="unique_gl_integration_source",
                    )
                ],
            },
        ),
    ]
