# Generated by Django 5.2.7 on 2026-04-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockfinder", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockfindersynclog",
            name="config",
        ),
        migrations.RemoveField(
            model_name="stockfinderstockitem",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="stockfinderstockitem",
            name="local_stock_item",
        ),
        migrations.RemoveField(
            model_name="stockfinderstockitem",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="stockfindersynclog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="stockfindersynclog",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="stockfinderwebhookevent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="stockfinderwebhookevent",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="StockFinderConfig",
        ),
        migrations.DeleteModel(
            name="StockFinderStockItem",
        ),
        migrations.DeleteModel(
            name="StockFinderSyncLog",
        ),
        migrations.DeleteModel(
            name="StockFinderWebhookEvent",
        ),
    ]
