# Generated by Django 5.2.7 on 2026-01-30 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debtors', '0001_initial'),
        ('settings', '0001_initial'),
        ('stock_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotelineitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_lines', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.taxcode'),
        ),
        migrations.AddField(
            model_name='creditnotelineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtor',
            name='area_salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to='settings.salesarea'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtor',
            name='credit_terms',
            field=models.ForeignKey(help_text='Payment terms (30/60/90 days)', on_delete=django.db.models.deletion.PROTECT, related_name='debtors', to='settings.creditterms'),
        ),
        migrations.AddField(
            model_name='debtor',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deactivated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtor',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='debtorjournal',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtorjournal',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='debtorjournal',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtorjournal',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtoropenitem',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='debtors.creditnote'),
        ),
        migrations.AddField(
            model_name='debtoropenitem',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='debtoropenitem',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='debtors.debtorjournal'),
        ),
        migrations.AddField(
            model_name='debtorreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtorreceipt',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='debtorreceipt',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.paymentmethod'),
        ),
        migrations.AddField(
            model_name='debtorreceipt',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtorreceipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestcharge',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestcharge',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='interestcharge',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestcharge',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtoropenitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='open_items', to='debtors.invoice'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='debtors.invoice'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='debtors.invoice'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='stock_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='stock_control.stockitem'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings.taxcode'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openitemallocation',
            name='open_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='debtors.debtoropenitem'),
        ),
        migrations.AddField(
            model_name='openitemallocation',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='debtors.debtorreceipt'),
        ),
        migrations.AddField(
            model_name='postdatedcheque',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postdatedcheque',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_dated_cheques', to='debtors.debtor'),
        ),
        migrations.AddField(
            model_name='postdatedcheque',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_pdc', to='debtors.debtorreceipt'),
        ),
        migrations.AddField(
            model_name='postdatedcheque',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='creditnotelineitem',
            unique_together={('credit_note', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['account_number'], name='debtors_account_330ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['search_name'], name='debtors_search__af3332_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['name'], name='debtors_name_7868e4_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['is_active'], name='debtors_is_acti_0be491_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['account_category'], name='debtors_account_79ef97_idx'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['area_salesman'], name='debtors_area_sa_f8f323_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['debtor', 'transaction_date'], name='debtor_invo_debtor__95043a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_posted'], name='debtor_invo_is_post_1a6bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['transaction_number'], name='debtor_invo_transac_155fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='debtoropenitem',
            index=models.Index(fields=['debtor', 'is_fully_allocated'], name='debtor_open_debtor__21aeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='debtoropenitem',
            index=models.Index(fields=['transaction_date'], name='debtor_open_transac_f6888d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicelineitem',
            unique_together={('invoice', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='postdatedcheque',
            index=models.Index(fields=['debtor', 'is_processed'], name='post_dated__debtor__8ff0c3_idx'),
        ),
        migrations.AddIndex(
            model_name='postdatedcheque',
            index=models.Index(fields=['cheque_date'], name='post_dated__cheque__b70499_idx'),
        ),
    ]
