# Generated by Django 5.2.7 on 2026-02-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='account_type',
            field=models.CharField(blank=True, choices=[('', 'Balance Brought Forward'), ('O', 'Open Item'), ('C', 'Cash Customer'), ('N', 'Normal Credit'), ('B', 'COD')], db_column='acctype', default='', help_text='Account Type (ACCTYPE) - Blank=Balance Forward, O=Open Item, C=Cash, N=Normal, B=COD', max_length=1),
        ),
    ]
