# Generated by Django 5.2.7 on 2026-03-05 19:01

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0002_alter_debtoraudit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtor',
            options={'ordering': ['dno'], 'verbose_name': 'Debtor', 'verbose_name_plural': 'Debtors'},
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='idx_dno',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='idx_dsname',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='idx_dname',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='idx_darea',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='idx_blockflag',
        ),
        migrations.RemoveIndex(
            model_name='debtor',
            name='idx_balance_curr',
        ),
        migrations.RenameField(
            model_name='debtor',
            old_name='prompt_payment_discount',
            new_name='pdisc',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='balance_120_days',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='balance_150_days',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='balance_180_days',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='balance_30_days',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='balance_60_days',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='balance_90_days',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='balance_brought_forward',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='balance_current',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='block_flag',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='customer_number',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='date_opened',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='interest_flag',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='last_payment_amount',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='positive_balance_only',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='price_level',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='profit_month',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='profit_year',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='sales_month',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='sales_year',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='tax_number',
        ),
        migrations.RemoveField(
            model_name='debtor',
            name='vat_reference',
        ),
        migrations.AddField(
            model_name='debtor',
            name='acctype',
            field=models.CharField(blank=True, choices=[('', 'Balance Brought Forward'), ('O', 'Open Item'), ('C', 'Cash Customer'), ('N', 'Normal Credit'), ('B', 'COD')], default='', help_text='Account Type (ACCTYPE) - Blank=Balance Forward, O=Open Item, C=Cash, N=Normal, B=COD', max_length=1),
        ),
        migrations.AddField(
            model_name='debtor',
            name='blockflag',
            field=models.CharField(choices=[('0', 'Active'), ('1', 'Credit Hold'), ('2', 'Closed'), ('3', 'No Delivery'), ('Y', 'Blocked'), ('N', 'Active Legacy')], default='0', help_text='Block Account (BLOCKFLAG) - 0=Active, 1=Credit Hold, 2=Closed, 3=No Delivery', max_length=1),
        ),
        migrations.AddField(
            model_name='debtor',
            name='d120',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='120 Days Balance (D120) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='d150',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='150 Days Balance (D150) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='d180',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='180+ Days Balance (D180) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='d30',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='30 Days Balance (D30) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='d60',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='60 Days Balance (D60) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='d90',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='90 Days Balance (D90) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='damtlpd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of Last Payment (DAMTLPD) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='darea',
            field=models.IntegerField(blank=True, help_text='Salesman/Area Number (DAREA) - Numeric 2', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dateopened',
            field=models.DateField(blank=True, help_text='Date Account Opened (DATEOPENED) - Date 8', null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dbalbfwd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance Brought Forward (DBALBFWD) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dclimit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit Limit (DCLIMIT) - Numeric 12.2', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dcontact',
            field=models.CharField(blank=True, help_text='Contact Person (DCONTACT) - Character 20', max_length=50),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dcrnt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current Month Balance (DCRNT) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='ddatlpd',
            field=models.DateField(blank=True, help_text='Date of Last Payment (DDATLPD) - Date 8', null=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='ddiscper',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard Discount % (DDISCPER) - Numeric 10.2', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dfax',
            field=models.CharField(blank=True, help_text='Fax Number (DFAX) - Character 15', max_length=20),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dintflag',
            field=models.CharField(choices=[('Y', 'Yes - Charge Interest'), ('N', 'No - Do Not Charge')], default='N', help_text='Charge Interest (DINTFLAG) - Y/N', max_length=1),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dname',
            field=models.CharField(default=django.utils.timezone.now, help_text='Customer/Debtor Name (DNAME) - Character 40', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtor',
            name='dno',
            field=models.IntegerField(db_index=True, default=django.utils.timezone.now, help_text='Debtor Account Number (DNO) - Numeric 5', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtor',
            name='dposbal',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Print Account Balance on POS (DPOSBAL) - Y/N', max_length=1),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dprofitm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit for Current Month (DPROFITM) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dprofity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Profit for Year (DPROFITY) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dsalesm',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sales Total for Current Month (DSALESM) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dsalesy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sales Total for Year (DSALESY) - Numeric 10.2', max_digits=12),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dsname',
            field=models.CharField(blank=True, db_index=True, help_text='Short/Sort Name (DSNAME) - Character 5', max_length=20),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dtaxno',
            field=models.CharField(blank=True, help_text='Tax/Company Registration Number (DTAXNO) - Character 20', max_length=30),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dtel',
            field=models.CharField(blank=True, help_text='Telephone Number (DTEL) - Character 15', max_length=20),
        ),
        migrations.AddField(
            model_name='debtor',
            name='dtel2',
            field=models.CharField(blank=True, help_text='Alternative Phone (TEL2) - Character 15', max_length=20),
        ),
        migrations.AddField(
            model_name='debtor',
            name='price',
            field=models.IntegerField(choices=[(1, 'Retail'), (2, 'Trade'), (3, 'Wholesale')], default=1, help_text='Price Level (PRICE) - Numeric 1 (1=Retail, 2=Trade, 3=Wholesale)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='debtor',
            name='terms',
            field=models.IntegerField(default=30, help_text='Payment Terms in Days (TERMS) - Numeric 3', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='debtor',
            name='vatref',
            field=models.CharField(blank=True, help_text='VAT Registration Number (VATREF) - Character 10', max_length=20),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['dno'], name='idx_dno'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['dsname'], name='idx_dsname'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['dname'], name='idx_dname'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['darea'], name='idx_darea'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['blockflag'], name='idx_blockflag'),
        ),
        migrations.AddIndex(
            model_name='debtor',
            index=models.Index(fields=['-dcrnt'], name='idx_balance_curr'),
        ),
    ]
