# Generated by Django 5.2.7 on 2026-03-25 19:04

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debtors", "0003_alter_debtor_options_remove_debtor_idx_dno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="darea",
            name="arsls1",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls10",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls11",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls12",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls2",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls3",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls4",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls5",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls6",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls7",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls8",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="darea",
            name="arsls9",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="debtopen",
            name="ageflag",
            field=models.CharField(
                choices=[
                    ("0", "Current"),
                    ("1", "30 Days"),
                    ("2", "60 Days"),
                    ("3", "90 Days"),
                    ("4", "120+ Days"),
                ],
                default="0",
                help_text="Aging flag (AGEFLAG)",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="debtopen",
            name="balancedue",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Balance due on transaction (BALANCEDUE)",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="debtopen",
            name="date",
            field=models.DateField(
                db_index=True, help_text="Date of transaction (DATE)"
            ),
        ),
        migrations.AlterField(
            model_name="debtopen",
            name="dtrano",
            field=models.CharField(
                help_text="Transaction number (DTRANO)", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="debtopen",
            name="posted",
            field=models.CharField(
                default="N", help_text="Posted status (POSTED)", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="debtopen",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Original transaction total (TOTAL)",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="debtopen",
            name="type",
            field=models.CharField(
                choices=[
                    ("IN", "Invoice"),
                    ("CN", "Credit Note"),
                    ("PY", "Payment"),
                    ("JD", "Journal Debit"),
                    ("JC", "Journal Credit"),
                    ("DM", "Debit Memo"),
                    ("CM", "Credit Memo"),
                ],
                help_text="Transaction type (TYPE)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="acctype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Balance Brought Forward"),
                    ("O", "Open Item"),
                    ("C", "Cash Customer"),
                    ("N", "Normal Credit"),
                    ("B", "COD"),
                ],
                default="",
                help_text="Account Type (ACCTYPE)",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="blockflag",
            field=models.CharField(
                choices=[
                    ("0", "Active"),
                    ("1", "Credit Hold"),
                    ("2", "Closed"),
                    ("3", "No Delivery"),
                    ("Y", "Blocked"),
                    ("N", "Active Legacy"),
                ],
                default="0",
                help_text="Block Account (BLOCKFLAG)",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="dtel2",
            field=models.CharField(
                blank=True,
                db_column="dtel2",
                default="",
                help_text="Alternative Phone (TEL2) - Character 15",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="debtor",
            name="price",
            field=models.IntegerField(
                choices=[(1, "Retail"), (2, "Trade"), (3, "Wholesale")],
                default=1,
                help_text="Price Level (PRICE) - Numeric 1",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="debtoraudit",
            name="amount",
            field=models.DecimalField(
                db_column="amount",
                decimal_places=2,
                help_text="Audit amount (AMOUNT)",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="debtoraudit",
            name="date",
            field=models.DateField(
                db_column="date", db_index=True, help_text="Audit date (DATE)"
            ),
        ),
        migrations.AlterField(
            model_name="debtoraudit",
            name="dtrano",
            field=models.CharField(
                db_column="dtrano",
                help_text="Transaction number (DTRANO)",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="debtoraudit",
            name="thistran",
            field=models.CharField(
                db_column="thistran",
                help_text="Current transaction type identifier (THISTRAN)",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="debtoraudit",
            name="thistype",
            field=models.CharField(
                choices=[
                    ("IN", "Invoice"),
                    ("CR", "Credit Note"),
                    ("PA", "Payment"),
                    ("AD", "Adjustment"),
                    ("DM", "Debit Memo"),
                    ("CM", "Credit Memo"),
                    ("AL", "Allocation"),
                ],
                db_column="thistype",
                help_text="Current transaction type (THISTYPE)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="debtoraudit",
            name="type",
            field=models.CharField(
                choices=[
                    ("IN", "Invoice"),
                    ("CR", "Credit Note"),
                    ("PA", "Payment"),
                    ("AD", "Adjustment"),
                    ("DM", "Debit Memo"),
                    ("CM", "Credit Memo"),
                    ("AL", "Allocation"),
                ],
                db_column="type",
                help_text="Transaction type (TYPE)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="debtoropenitem",
            name="age_flag",
            field=models.CharField(
                choices=[
                    ("0", "Current"),
                    ("1", "30 Days"),
                    ("2", "60 Days"),
                    ("3", "90 Days"),
                    ("4", "120+ Days"),
                ],
                db_column="ageflag",
                default="0",
                help_text="Aging Flag (AGEFLAG)",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="debtoropenitem",
            name="balance_due",
            field=models.DecimalField(
                db_column="balancedue",
                decimal_places=2,
                help_text="Current Balance Due (BALANCEDUE)",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="debtoropenitem",
            name="original_amount",
            field=models.DecimalField(
                db_column="total",
                decimal_places=2,
                help_text="Original Transaction Total (TOTAL)",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="debtoropenitem",
            name="posted",
            field=models.CharField(
                db_column="posted",
                default="Y",
                help_text="Posted Status (POSTED)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="debtoropenitem",
            name="transaction_date",
            field=models.DateField(
                db_column="date", db_index=True, help_text="Transaction Date (DATE)"
            ),
        ),
        migrations.AlterField(
            model_name="debtoropenitem",
            name="transaction_number",
            field=models.CharField(
                db_column="dtrano",
                help_text="Transaction Number (DTRANO)",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="debtoropenitem",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("IN", "Invoice"),
                    ("CN", "Credit Note"),
                    ("PY", "Payment"),
                    ("JD", "Journal Debit"),
                    ("JC", "Journal Credit"),
                    ("DM", "Debit Memo"),
                    ("CM", "Credit Memo"),
                ],
                db_column="type",
                help_text="Transaction Type (TYPE)",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="customer_reference",
            field=models.CharField(
                blank=True,
                db_column="custref",
                help_text="Customer Reference (CUSTREF)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="description_line1",
            field=models.CharField(
                blank=True,
                db_column="del1",
                help_text="Delivery/Description Line 1 (DEL1)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="description_line2",
            field=models.CharField(
                blank=True,
                db_column="del2",
                help_text="Delivery/Description Line 2 (DEL2)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="description_line3",
            field=models.CharField(
                blank=True,
                db_column="del3",
                help_text="Delivery/Description Line 3 (DEL3)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="description_line4",
            field=models.CharField(
                blank=True,
                db_column="del4",
                help_text="Delivery/Description Line 4 (DEL4)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="order_number",
            field=models.CharField(
                blank=True,
                db_column="ordno",
                help_text="Order Number (ORDNO)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="source_reference",
            field=models.CharField(
                blank=True, help_text="Link to original record", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="source_station",
            field=models.PositiveIntegerField(
                db_column="source",
                default=0,
                help_text="Station/Till Number (SOURCE)",
                validators=[django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("POS", "Point of Sale"),
                    ("INVOICE", "Invoice Entry"),
                    ("IMPORT", "Bulk Import"),
                    ("MANUAL", "Manual Entry"),
                ],
                default="POS",
                help_text="Source of transaction",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="station",
            field=models.CharField(
                blank=True,
                db_column="station",
                help_text="Station Code (STATION)",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="subtotal",
            field=models.DecimalField(
                db_column="dtsub",
                decimal_places=2,
                help_text="Subtotal Excl. VAT (DTSUB)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="total_amount",
            field=models.DecimalField(
                db_column="dttot",
                decimal_places=2,
                help_text="Transaction Total Incl. VAT (DTTOT)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="transaction_time",
            field=models.TimeField(
                blank=True,
                db_column="time",
                help_text="Transaction Time (TIME)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="vat_amount",
            field=models.DecimalField(
                db_column="dtgst",
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="VAT Amount (DTGST)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="vat_reference",
            field=models.CharField(
                blank=True,
                db_column="vatref",
                help_text="VAT Reference (VATREF)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="debtortransaction",
            name="vat_status",
            field=models.CharField(
                choices=[
                    ("S", "Standard Rated (15%)"),
                    ("E", "Exempt"),
                    ("Z", "Zero Rated"),
                ],
                db_column="dtaxstat",
                default="S",
                help_text="VAT Status (DTAXSTAT)",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dpdc",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cheque value",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="dpdc",
            name="date",
            field=models.DateField(db_index=True, help_text="Date of cheque"),
        ),
        migrations.AlterField(
            model_name="dpdc",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Active"),
                    ("I", "Inactive"),
                    ("P", "Processed"),
                    ("C", "Cancelled"),
                ],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="address_line1",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="address_line2",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="address_line3",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="amount_charged",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="comment_line1",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="comment_line2",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="comment_line3",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="comment_line4",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="contact_person",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="customer_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="debtor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_costings",
                to="debtors.debtor",
            ),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="job_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="odometer_reading",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="operator_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="order_number",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="salesman_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="station_completion",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="station_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(99)],
            ),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="status",
            field=models.CharField(
                choices=[("A", "Active"), ("C", "Cancelled"), ("D", "Complete")],
                default="A",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="telephone",
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="time_completed",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="time_start",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="total_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="transaction_number",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(999999)],
            ),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="transaction_type",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="vehicle_make_model",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="jobcosting",
            name="vehicle_registration",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="code",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="comments",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="department",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="job_costing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="debtors.jobcosting",
            ),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="selling_price",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="tax_code",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="jobcostingtransaction",
            name="transaction_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="jobprinting",
            name="job_cards_station",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="jobprinting",
            name="job_invoices_station",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="jobprinting",
            name="job_reports_station",
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
