# Generated by Django 5.2.7 on 2026-03-27 16:37
#
# NOTE: This used to just AddField(tel2), while 0007 ran ALTER COLUMN
# statements against tel2 before this AddField had run - always failing
# on a fresh apply with "column tel2 does not exist". The AddField moved
# to 0007 and this now carries the ALTER COLUMN statements that used to
# be in 0007, so they run after the column exists.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0007_fix_tel2_default'),
    ]

    operations = [
        # Drop NOT NULL, set DEFAULT, then re-add NOT NULL
        migrations.RunSQL(
            sql="ALTER TABLE dmast ALTER COLUMN tel2 DROP NOT NULL;",
            reverse_sql="ALTER TABLE dmast ALTER COLUMN tel2 SET NOT NULL;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE dmast ALTER COLUMN tel2 SET DEFAULT '';",
            reverse_sql="ALTER TABLE dmast ALTER COLUMN tel2 DROP DEFAULT;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE dmast ALTER COLUMN tel2 SET NOT NULL;",
            reverse_sql="ALTER TABLE dmast ALTER COLUMN tel2 DROP NOT NULL;"
        ),
    ]
