# Generated by Django 5.2.7 on 2026-03-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0007_fix_tel2_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='tel2',
            field=models.CharField(blank=True, db_column='tel2', default='', help_text='Legacy duplicate of dtel2 (TEL2)', max_length=20),
        ),
    ]
