# Generated by Django 5.2.7 on 2026-08-26 09:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtors', '0009_dpdc_cheque_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debtortransaction',
            name='settlement_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Settlement/prompt-payment discount granted on this receipt (RCP transactions only)', max_digits=12),
        ),
        migrations.CreateModel(
            name='ReceiptAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('settlement_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('open_item', models.ForeignKey(help_text='The open item (invoice/etc.) this allocation was applied to', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='debtors.debtopen')),
                ('receipt', models.ForeignKey(help_text='The RCP DebtorTransaction this allocation was made from', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='debtors.debtortransaction')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'debtor_receipt_allocations',
                'ordering': ['allocated_at'],
                'indexes': [models.Index(fields=['receipt'], name='debtor_rece_receipt_02ffe1_idx'), models.Index(fields=['open_item'], name='debtor_rece_open_it_c61799_idx')],
            },
        ),
    ]
