# Generated by Django 5.2.7 on 2026-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debtors", "0010_debtortransaction_settlement_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtortransaction",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("POS", "Point of Sale"),
                    ("INVOICE", "Invoice Entry"),
                    ("CREDIT_NOTE", "Credit Note Entry"),
                    ("IMPORT", "Bulk Import"),
                    ("MANUAL", "Manual Entry"),
                ],
                default="POS",
                help_text="Source of transaction",
                max_length=20,
            ),
        ),
    ]
