# Generated by Django 5.2.7 on 2026-08-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debtors", "0011_alter_debtortransaction_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtoraudit",
            name="thistype",
            field=models.CharField(
                choices=[
                    ("IN", "Invoice"),
                    ("CN", "Credit Note"),
                    ("CS", "Cash Sale"),
                    ("CR", "Cash Return"),
                    ("PM", "Payment"),
                    ("RCP", "Receipt"),
                    ("INT", "Interest Charge"),
                    ("JD", "Journal Debit"),
                    ("JC", "Journal Credit"),
                    ("RF", "Refund"),
                    ("PA", "Payment (legacy)"),
                    ("AD", "Adjustment"),
                    ("DM", "Debit Memo"),
                    ("CM", "Credit Memo"),
                    ("AL", "Allocation"),
                ],
                db_column="thistype",
                help_text="Current transaction type (THISTYPE)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="debtoraudit",
            name="type",
            field=models.CharField(
                choices=[
                    ("IN", "Invoice"),
                    ("CN", "Credit Note"),
                    ("CS", "Cash Sale"),
                    ("CR", "Cash Return"),
                    ("PM", "Payment"),
                    ("RCP", "Receipt"),
                    ("INT", "Interest Charge"),
                    ("JD", "Journal Debit"),
                    ("JC", "Journal Credit"),
                    ("RF", "Refund"),
                    ("PA", "Payment (legacy)"),
                    ("AD", "Adjustment"),
                    ("DM", "Debit Memo"),
                    ("CM", "Credit Memo"),
                    ("AL", "Allocation"),
                ],
                db_column="type",
                help_text="Transaction type (TYPE)",
                max_length=3,
            ),
        ),
    ]
