# Generated by Django 5.2.7 on 2026-08-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debtors", "0012_alter_debtoraudit_thistype_alter_debtoraudit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debtopen",
            name="type",
            field=models.CharField(
                choices=[
                    ("IN", "Invoice"),
                    ("CN", "Credit Note"),
                    ("PY", "Payment"),
                    ("RCP", "Receipt"),
                    ("INT", "Interest Charge"),
                    ("JD", "Journal Debit"),
                    ("JC", "Journal Credit"),
                    ("DM", "Debit Memo"),
                    ("CM", "Credit Memo"),
                ],
                help_text="Transaction type (TYPE)",
                max_length=3,
            ),
        ),
    ]
