# Generated by Django 5.2.7 on 2026-02-08 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='current_financial_year',
            field=models.PositiveIntegerField(default=2024, help_text='Current financial year (e.g., 2024)'),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, help_text='Default tax code for new items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_configs', to='settings.taxcode'),
        ),
    ]
