# Generated by Django 5.2.7 on 2026-02-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p1',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 1', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p10',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 10', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p11',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 11', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p12',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 12', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p2',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 2', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p3',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 3', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p4',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 4', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p5',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 5', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p6',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 6', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p7',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 7', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p8',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 8', max_digits=15),
        ),
        migrations.AddField(
            model_name='salesdepartment',
            name='sales_p9',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Sales Period 9', max_digits=15),
        ),
    ]
