# Generated by Django 5.2.7 on 2026-02-05 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='costingcategory',
            index=models.Index(fields=['costing_method'], name='costing_cat_costing_373b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='costingcategory',
            index=models.Index(fields=['pricing_method'], name='costing_cat_pricing_d791c5_idx'),
        ),
        migrations.AddIndex(
            model_name='costingcategory',
            index=models.Index(fields=['costing_method', 'pricing_method'], name='costing_cat_costing_c592e8_idx'),
        ),
        migrations.AddIndex(
            model_name='costingcategory',
            index=models.Index(fields=['is_active'], name='costing_cat_is_acti_1b4d38_idx'),
        ),
        migrations.AddIndex(
            model_name='creditterms',
            index=models.Index(fields=['days'], name='credit_term_days_402cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='creditterms',
            index=models.Index(fields=['is_active'], name='credit_term_is_acti_48b4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['number'], name='expense_cat_number_a1c805_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['name'], name='expense_cat_name_510d25_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['category_type'], name='expense_cat_categor_466692_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['is_active'], name='expense_cat_is_acti_421191_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['number'], name='income_cate_number_382536_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['name'], name='income_cate_name_5f5d72_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['is_active'], name='income_cate_is_acti_4ca438_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['code'], name='payment_met_code_b70caa_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['is_active'], name='payment_met_is_acti_395fa6_idx'),
        ),
    ]
