# Generated by Django 5.2.7 on 2026-02-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_apikey'),
        ('settings', '0002_salesdepartment_sales_p1_salesdepartment_sales_p10_and_more'),
    ]

    operations = [
    ]
