# Generated by Django 5.2.7 on 2026-02-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_merge_20260222_1416"),
        ("tenancy", "0010_shop_setup_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Tenant this API key belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="tenancy.tenant",
            ),
        ),
    ]
