# Generated by Django 5.2.7 on 2026-02-16 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_apikey'),
        ('tenancy', '0010_shop_setup_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this API key belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['tenant', 'status'], name='settings_ap_tenant__9ba903_idx'),
        ),
    ]
