# Generated by Django 5.2.7 on 2026-08-11 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_systemconfiguration_day_end_day_of_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayEndReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_date', models.DateField()),
                ('shop_id', models.IntegerField(blank=True, help_text='Shop filter used for this run, if any', null=True)),
                ('success', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Day End Report',
                'verbose_name_plural': 'Day End Reports',
                'db_table': 'day_end_reports',
                'ordering': ['-process_date'],
                'indexes': [models.Index(fields=['process_date'], name='day_end_rep_process_1c5568_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('shop_id__isnull', False)), fields=('process_date', 'shop_id'), name='unique_day_end_report_per_shop'), models.UniqueConstraint(condition=models.Q(('shop_id__isnull', True)), fields=('process_date',), name='unique_day_end_report_tenant_wide')],
            },
        ),
    ]
