# Generated by Django 5.2.7 on 2026-08-30 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_dayendreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensecategory",
            name="gl_accno",
            field=models.BigIntegerField(
                blank=True,
                help_text="GLMast.accno this category posts to via GL Integration Transfer. Falls back to GLIntegrationSettings.cashbook_default_expense_accno when unset.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="incomecategory",
            name="gl_accno",
            field=models.BigIntegerField(
                blank=True,
                help_text="GLMast.accno this category posts to via GL Integration Transfer. Falls back to GLIntegrationSettings.cashbook_default_income_accno when unset.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999999),
                ],
            ),
        ),
    ]
